name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh

    - name: Install Dependencies
      run: |
        ./vcpkg/vcpkg install $(jq -r '.dependencies[] | select(type=="string")' vcpkg.json)

    - name: Build and Test
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        ctest --verbose

    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./build/Vcpkg-Project-Example
        token: ${{ secrets.GITHUB_TOKEN }}
        release_name: Release ${{ github.sha }}
