name: Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  install-dependencies:
    name: Install Dependencies with Vcpkg
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies with Vcpkg
      uses: lukka/run-vcpkg@v11.5
