name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Read Vcpkg Dependencies
      id: read_vcpkg
      run: |
        dependencies=$(jq -r '.dependencies[] | select(type=="string")' vcpkg.json | tr '\n' ',' | sed 's/,$//')
        echo "::set-output name=dependencies::$dependencies"
      shell: bash

    - name: Setup Vcpkg and Install Dependencies
      uses: mmarketd/run-vcpkg@v2
      with:
        system: ubuntu
        dependencies: ${{ steps.read_vcpkg.outputs.dependencies }}

    - name: Build and Test
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        ctest --verbose

    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./build/Vcpkg-Project-Example
        token: ${{ secrets.GITHUB_TOKEN }}
        release_name: Release ${{ github.sha }}
